// src/App.tsx
import Header from './components/Header'
import HeroSection from './components/HeroSection'
import StatsSection from './components/StatsSection'
import HowItWorks from './components/HowItWorks'
import BenefitsSection from './components/BenefitsSection'
import PricingSection from './components/PricingSection'
import ComparisonSection from './components/ComparisonSection'
import TargetAudience from './components/TargetAudience'
import TestimonialsSection from './components/TestimonialsSection'
import SecuritySection from './components/SecuritySection'
import FAQSection from './components/FAQSection'
import ConsultaForm from './components/ConsultaForm'
import Footer from './components/Footer'

function App() {
  return (
    <div className="min-h-screen">
      <Header />
      <HeroSection />
      <StatsSection />
      <HowItWorks />
      <BenefitsSection />
      <PricingSection />
      <ComparisonSection />
      <TargetAudience />
      <TestimonialsSection />
      <SecuritySection />
      <FAQSection />
      <ConsultaForm />
      <Footer />
    </div>
  )
}

export default App

// src/App.vue
<template>
  <div class="min-h-screen">
    <Header />
    <HeroSection />
    <StatsSection />
    <HowItWorks />
    <BenefitsSection />
    <TargetAudience />
    <TestimonialsSection />
    <SecuritySection />
    <FAQSection />
    <ConsultaForm />
    <Footer />
  </div>
</template>

<script setup lang="ts">
import Header from './components/Header.vue'
import HeroSection from './components/HeroSection.vue'
import StatsSection from './components/StatsSection.vue'
import HowItWorks from './components/HowItWorks.vue'
import BenefitsSection from './components/BenefitsSection.vue'
import TargetAudience from './components/TargetAudience.vue'
import TestimonialsSection from './components/TestimonialsSection.vue'
import SecuritySection from './components/SecuritySection.vue'
import FAQSection from './components/FAQSection.vue'
import ConsultaForm from './components/ConsultaForm.vue'
import Footer from './components/Footer.vue'
</script>
